apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ipythonconf
data:
  ipcontroller_config.py: |
    # Configuration file for ipcontroller.

    c = get_config()

    c.IPController.ip = '*'

    c.IPController.engine_json_file="/home/jupyter/my-nfs/ipcontroller-engine.json"

    c.IPController.location="{{ .Release.Name }}-frontend-service.default.svc.cluster.local"

    c.IPController.client_json_file="/home/jupyter/my-nfs/ipcontroller-client.json"

    c.IPController.ports=[
    {{- range concat .Values.frontend.enginePorts .Values.frontend.clientPorts }}
      {{ .port }},
    {{- end }}
    ]

    # c.IPController.db_class='ipyparallel.controller.dictdb.NoDB'

  ipengine_config.py: |
    # Configuration file for ipengine.

    c = get_config()

    c.IPEngine.url_file="/home/jupyter/my-nfs/ipcontroller-engine.json"
