apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ipythonconf
data:
  ipcontroller_config.py: |
    # Configuration file for ipcontroller.
    import os

    c = get_config()

    c.IPController.log_datefmt = {{ include "myapp.formatValue" .Values.frontend.IPController.logger.log_datefmt}}
    c.IPController.log_format = {{ include "myapp.formatValue" .Values.frontend.IPController.logger.log_format}}
    c.IPController.log_level = {{ include "myapp.formatValue" .Values.frontend.IPController.logger.log_level}}
    c.IPController.log_to_file = {{ include "myapp.formatValue" .Values.frontend.IPController.logger.log_to_file}}
    c.IPController.debug = {{ include "myapp.formatValue" .Values.frontend.IPController.logger.include_all_heartbeats}}
    c.IPController.verbose_crash = {{ include "myapp.formatValue" .Values.frontend.IPController.logger.verbose_crash}}

    c.IPController.registration_timeout = {{ include "myapp.formatValue" .Values.frontend.IPController.heartmonitor.registration_timeout}}
    c.IPController.heartmonitor_period = {{ include "myapp.formatValue" .Values.frontend.IPController.heartmonitor.heartmonitor_period}}
    c.IPController.max_heartmonitor_misses = {{ include "myapp.formatValue" .Values.frontend.IPController.heartmonitor.max_heartmonitor_misses}}

    c.IPController.db_class = {{ include "myapp.formatValue" .Values.frontend.IPController.db.db_class}}


    c.IPController.ip = '*'

    ip_controller_json_dir = os.environ["IPCONTROLLER_JSON_DIR"]
    c.IPController.engine_json_file=ip_controller_json_dir+"/ipcontroller-engine.json"

    c.IPController.location="{{ .Release.Name }}-frontend-service.default.svc.cluster.local"

    c.IPController.client_json_file=ip_controller_json_dir+"/ipcontroller-client.json"

    c.IPController.ports=[
    {{- range concat .Values.frontend.IPController.enginePorts .Values.frontend.IPController.clientPorts }}
      {{ .port }},
    {{- end }}
    ]
  ipengine_config.py: |
    # Configuration file for ipengine.
    import os

    c = get_config()

    ip_controller_json_dir = os.environ["IPCONTROLLER_JSON_DIR"]
    c.IPEngine.url_file=ip_controller_json_dir+"/ipcontroller-engine.json"

  jupyterhub_config.py: |
    # Configuration file for jupyterhub.

    c = get_config()
    c.Authenticator.allow_all = True
    c.Authenticator.allowed_users = { {{- range .Values.users }} '{{ .username }}', {{- end }} }