version: "3.8"

services:

  head-node:
    image: debian-slurm-hn:latest
    container_name: slurm-head-node
    hostname: linux-hn
    expose:
      - "6817"

  compute-node1:
    image: debian-slurm-cn:latest
    container_name: slurm-compute-node1
    hostname: linux-1
    expose:
      - "6818"
    depends_on:
      - "head-node"

  compute-node2:
    image: debian-slurm-cn:latest
    container_name: slurm-compute-node2
    hostname: linux-2
    expose:
      - "6818"
    depends_on:
      - "head-node"