apiVersion: v1
kind: ConfigMap
metadata:
  name: ipythonconf-wn
data:
  ipcontroller-engine.json: |
    {
      "ssh": "",
      "interface": "tcp://my-service.default.svc.cluster.local",
      "registration": 58173,
      "control": 36827,
      "mux": 51387,
      "task": 33439,
      "iopub": 33613,
      "hb_ping": 34595,
      "hb_pong": 56171,
      "broadcast": [
        59031,
        56287
      ],
      "key": "9f8d6a2f-34485b850956c550ef9c68e7",
      "curve_serverkey": null,
      "location": "frontend",
      "pack": "json",
      "unpack": "json",
      "signature_scheme": "hmac-sha256"
    }

