{{- if .Values.db.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-db
  labels:
    type: db-node
spec:
  # securityContext:
  #   runAsUser: 1002
  hostname: {{ include "slurm.db.hostname" . }}
  initContainers:
    - name: init-copy-permissions
      image: busybox
      command: ["ash","-c"]
      args: ["cp              /config/slurmdbd.conf    /etc/slurm/slurmdbd.conf && \
              cp              /config/slurm.conf       /etc/slurm/slurm.conf    && \
              chown 1002:1002 /etc/slurm/slurmdbd.conf /etc/slurm/slurm.conf    && \
              chmod 600       /etc/slurm/slurmdbd.conf /etc/slurm/slurm.conf"]
      volumeMounts:
        - name: config-volume
          mountPath: /config/
        - name: emptydir-volume
          mountPath: /etc/slurm
  containers:
    - name: slurmdbd
      image: agalrui/debian-slurm-db:{{ if .Values.benchmark }}benchmark{{ else }}latest{{ end }}
      # command: ["tail", "-f", "/dev/null"]
      env:
        - name: MYSQL_ADDRESS
          value: {{ .Values.db.address }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_SLURM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: slurm-password
      volumeMounts:
        - name: emptydir-volume
          mountPath: /etc/slurm/

    - name: mysql
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_DATABASE
          value: slurmdb
        - name: MYSQL_USER
          value: slurm
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: slurm-password
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql

  volumes:
    - name: config-volume
      configMap:
        defaultMode: 0600
        name: {{ .Release.Name }}-slurm-conf
        items:
        - key: slurm.conf
          path: slurm.conf
        - key: slurmdbd.conf
          path: slurmdbd.conf
    - name: emptydir-volume
      emptyDir: {}
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: {{ .Release.Name }}-db-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "slurm.db.hostname" . }}
spec:
  clusterIP: None
  selector:
    type: db-node
  ports:
    - name: listen
      port: {{ .Values.db.slurmdbdPort }}
      targetPort: {{ .Values.db.slurmdbdPort }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/slurm-db"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


{{- end }}