apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    type: head-node
spec:
  hostname: {{ include "slurm.frontend.hostname" . }}

  initContainers:
  {{- if .Values.nfs.useLocal }}
  - name: wait-for-nfs
    image: busybox
    command: ["sh","-c"]
    args: ["until nc -zv nfs-service 2049;
            do
              echo '-- nfs node (nfs-service) is not available.  Sleeping ...';
              sleep 5;
            done"]
  {{- end }}

  {{- if .Values.db.enabled }}
  - name: wait-for-db
    image: busybox
    command: ["sh","-c"]
    args: ["until nc -zv {{ include "slurm.db.hostname" . }} {{ .Values.db.slurmdbdPort }};
            do
              echo '-- db node ({{ include "slurm.db.hostname" . }}) is not available.  Sleeping ...';
              sleep 5;
            done"] 
  {{- end }}

  {{- if .Values.users }}
  - name: users-home-dir
    image: busybox
    command: ["sh", "-c"]
    args:
    - |
      {{- range $index, $user := .Values.users }}
      chown -R {{ add 1100 $index }}:{{ add 1100 $index }} /home/{{ $user.username }}
      {{- end }}
    volumeMounts:
    {{- range .Values.users }}
    - name: nfs-users-{{ .username }}
      mountPath: /home/{{ .username }}
    {{- end }}
  {{- end }}

  containers:
    - name: frontend
      image: agalrui/debian-slurm-hn:{{ if .Values.benchmark }}benchmark{{ else }}latest{{ end }}
      # securityContext:
      #   privileged: true
      # command: ["tail", "-f", "/dev/null"]
      command: ["/bin/sh", "/tmp/startup/startup-hn.sh"]

      volumeMounts:
        - name: config-volume
          mountPath: /etc/slurm/
        - name: config-users-volume
          mountPath: /etc/passwd
          subPath: passwd
        - name: config-users-volume
          mountPath: /etc/shadow
          subPath: shadow
        - name: config-users-volume
          mountPath: /etc/group
          subPath: group
        - name: config-users-volume
          mountPath: /etc/gshadow
          subPath: gshadow
        {{- range .Values.users }}
        - name: nfs-users-{{ .username }}
          mountPath: /home/{{ .username }}
        {{- end }}
        - name: startup-volume
          mountPath: /tmp/startup/

  volumes:
    {{- range .Values.users }}
    - name: nfs-users-{{ .username }}
      persistentVolumeClaim:
        claimName: pvc-users-{{ .username }}
    {{- end }}
    - name: config-volume
      configMap:
        defaultMode: 0777
        name: {{ .Release.Name }}-slurm-conf
        items:
        - key: slurm.conf
          path: slurm.conf
    - name: config-users-volume
      configMap:
        defaultMode: 0777
        name: {{ .Release.Name }}-users-config
    - name: startup-volume
      configMap:
        defaultMode: 0777
        name: {{ .Release.Name }}-startup
        items:
        - key: startup-hn.sh
          path: startup-hn.sh

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "slurm.frontend.hostname" . }}
spec:
  clusterIP: None
  selector:
    type: head-node
  ports:
    - name: listen
      port: {{ .Values.frontend.slurmctldPort }}
      targetPort: {{ .Values.frontend.slurmctldPort }}

---

apiVersion: v1
kind: Service
metadata:
  name: ssh-service
spec:
  type: NodePort
  selector:
    type: head-node
  ports:
    - port: 22
      targetPort: 22
      nodePort: 30022
