apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    type: head-node
spec:
  hostname: {{ include "slurm.frontend.hostname" . }}
  containers:
  - name: frontend
    image: agalrui/debian-slurm-hn
    # command: [ /bin/sh ]
    # args: [-c,while true;do sleep 20;done]
      

    volumeMounts:
    - name: frontend-volume
      mountPath: /etc/slurm/
  volumes:
  - name: frontend-volume
    configMap:
      defaultMode: 0777
      name: {{ .Release.Name }}-slurm-conf
      items:
      - key: slurm.conf
        path: slurm.conf

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "slurm.frontend.hostname" . }}
spec:
  clusterIP: None
  selector:
    type: head-node
  ports:
    - name: listen
      port: {{ .Values.frontend.slurmctldPort }}
      targetPort: {{ .Values.frontend.slurmctldPort }}