apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-startup
data:
  startup-cn.sh: |
    #!/usr/bin/env bash

    log() {

        echo "---> $1"
    }

    log_error() {

        echo "ERROR: $1"
    }

    log "Starting the Secure Shell daemon (sshd)  ..."
        /usr/sbin/sshd
        if ! pgrep -f sshd > /dev/null; then
            log_error "SSHD process is not running."
            exit 1
        fi

    log "Starting the MUNGE Authentication service (munged) ..."
        gosu munge /etc/init.d/munge start
        if ! pgrep -f munge > /dev/null; then
            log_error "MUNGE process is not running."
            exit 1
        fi

    log "Starting the Slurm Node Daemon (slurmd) ..."
        exec /usr/sbin/slurmd -Dvvv
        if ! pgrep -f slurmd > /dev/null; then
            log_error "SLURMD process is not running."
            exit 1
        fi

    log "Worker successfully started"  

    while :; do sleep 2073600 & wait; done

  
  startup-hn.sh: |
    #!/usr/bin/env bash

    log() {

        echo "---> $1"
    }

    log_error() {

        echo "ERROR: $1"
    }


    log "Starting the Secure Shell daemon (sshd)  ..."
        /usr/sbin/sshd
        if ! pgrep -f sshd > /dev/null; then
            log_error "SSHD process is not running."
            exit 1
        fi

    log "Starting the MUNGE Authentication service (munged) ..."
        gosu munge /etc/init.d/munge start
        if ! pgrep -f munge > /dev/null; then
            log_error "MUNGE process is not running."
            exit 1
        fi

    log "Starting the Slurm Node Daemon (slurmd) ..."
        exec gosu slurm /usr/sbin/slurmctld -Dvvv
        if ! pgrep -f sshd > /dev/null; then
            log_error "SLURMCTLD process is not running."
            exit 1
        fi

    log "Frontend successfully started"  

    while :; do sleep 2073600 & wait; done