apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-startup
data:
  startup-cn.sh: |
    #!/usr/bin/env bash

    echo "---> Starting the Secure Shell daemon (sshd)  ..."
        /usr/sbin/sshd

    echo "---> Starting the MUNGE Authentication service (munged) ..."
        sudo -u munge /etc/init.d/munge start

    # echo "---> Waiting for head node ({{ .Values.frontend.hostname }}) to become active before starting slurmd..."
    #     until 2>/dev/null >/dev/tcp/{{ .Values.frontend.hostname }}/6817
    #     do
    #         echo "-- head node ({{ .Values.frontend.hostname }}) is not available.  Sleeping ..."
    #         sleep 2
    #     done
    # echo "-- head node ({{ .Values.frontend.hostname }}) is now active ..."

    echo "---> Starting the Slurm Node Daemon (slurmd) ..."
        exec /usr/sbin/slurmd -Dvvv

    bash