apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-startup
data:
  startup-cn.sh: |
    #!/usr/bin/env bash

    echo "---> Starting the Secure Shell daemon (sshd)  ..."
        /usr/sbin/sshd

    echo "---> Starting the MUNGE Authentication service (munged) ..."
        sudo -u munge /etc/init.d/munge start

    # echo "---> Waiting for head node ({{ .Values.frontend.hostname }}) to become active before starting slurmd..."
    #     until 2>/dev/null >/dev/tcp/{{ .Values.frontend.hostname }}/6817
    #     do
    #         echo "-- head node ({{ .Values.frontend.hostname }}) is not available.  Sleeping ..."
    #         sleep 2
    #     done
    # echo "-- head node ({{ .Values.frontend.hostname }}) is now active ..."

    echo "---> Starting the Slurm Node Daemon (slurmd) ..."
        exec /usr/sbin/slurmd -Dvvv

    bash

  
  startup-hn.sh: |
    #!/usr/bin/env bash

    echo "---> Starting the Secure Shell daemon (sshd)  ..."
        /usr/sbin/sshd

    echo "---> Starting the MUNGE Authentication service (munged) ..."
        sudo -u munge /etc/init.d/munge start

    echo "---> Starting the Slurm Node Daemon (slurmd) ..."
        exec sudo -u slurm /usr/sbin/slurmctld -Dvvv

    bash
  
  startup-db.sh: |
    #!/usr/bin/env bash

    echo "---> Starting the Secure Shell daemon (sshd)  ..."
        /usr/sbin/sshd

    echo "---> Starting the MUNGE Authentication service (munged) ..."
        sudo -u munge /etc/init.d/munge start

    echo "---> Starting the mysql-server daemon (mysqld) ..."
        mysqld --user=mysql &

    echo -n "Waiting for MySQL to start..."
        while ! mysqladmin ping -h localhost; do
            echo -n "."
            sleep 1
        done
    echo "MySQL started successfully!"

    echo "--> Configurating mysql for slurm use ..."
    mysql -e "create user 'slurm'@'localhost' identified by '${MYSQL_SLURM_PASSWORD}';"
    mysql -e "grant all on slurm_acct_db.* TO 'slurm'@'localhost';"
    mysql -e "FLUSH PRIVILEGES;"
    mysql -e "CREATE DATABASE slurm_acct_db;"

    echo "--> Starting the slurm database daemon (slurmdbd) ..."
        sudo -u slurm slurmdbd -Dvvv

    bash


  