{{- range $index, $user := .Values.users }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-users-{{ .username }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-subdir
  nfs:
    server: {{ $.Values.nfsVolume.server}}
    path: {{ $.Values.nfsVolume.basePath}}/user_home_dir_{{ $index }}
    readOnly: false
---
{{- end }}

{{- range .Values.users }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-users-{{ .username }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-subdir
  resources:
    requests:
      storage: 100Mi
---
{{- end }}