# head node values
frontend:
  hostname: frontend-hn
  slurmctldPort: 6817 # https://slurm.schedmd.com/slurm.conf.html#OPT_SlurmctldPort

# compute nodes values
workers:
  baseHostname: lin
  slurmdPort: 6818 # https://slurm.schedmd.com/slurm.conf.html#OPT_SlurmdPort
  numReplicas: 3 # max 25

# db node values
db:
  enabled: true
  hostname: db-node         # Not needed if enabled is false
  slurmdbdPort: 6819        # Not needed if enabled is false
  mySqlPassword: password   # Not needed if enabled is false

nfs:
  useLocal: true
  server: 192.168.1.142           # Not needed if useLocal is true
  basePath: "/mnt/nfs_tfm/slurm"  # Not needed if useLocal is true

users:
  - username: test
    password: $6$5vOSBWhLiy78PwQ7$lyeJUp8F50IYJ0RjLVIfRYjPYffDGludEJf0wNITeCSgflVDhUc7Ho35m5PVl8dlno4kOqxYCafXJsT.STyWQ. #test
  - username: juan
    password: $6$sgH.CvbmRsXExWHL$kNv1POAJd8jzQY3OJ5DunXNVXzpJpCmMT60HxbTnfYfLPTf16ZcaQx4/e1yTth8w5HnG83l/iV8tLeN6lcGpf. #juan
  - username: pedro
    password: $6$edBhu1vMm7ZE3Fov$Q0reW6uZSOoSfe.eMlgOLhKO8qPZmkTZGbCBTewFuie8JwRWnGXEqg9BgTxDSB1iKqerJi8c.8WqXDQmFcHWI0 #pedro

benchmark: false