frontend:
  hostname: frontend
  IPController:
    logger:
      log_datefmt: "%Y-%m-%d %H:%M:%S"
      log_format: "[%(name)s]%(highlevel)s %(message)s"
      log_level: 30
      log_to_file: False
      include_all_heartbeats: False
      verbose_crash: False
    heartmonitor:
      registration_timeout: 30
      heartmonitor_period: 3000
      max_heartmonitor_misses: 10
    db:
      db_class: DictDB
    
    enginePorts:
      - name: registration
        port: 58173
      - name: control
        port: 36827
      - name: mux
        port: 51387
      - name: task
        port: 33439
      - name: iopub
        port: 33613
      - name: hb-ping
        port: 34595
      - name: hb-pong
        port: 56171
      - name: broadcast1
        port: 59031
      - name: broadcast2
        port: 56287
    clientPorts:
      - name: control
        port: 36605
      - name: mux
        port: 33125
      - name: task
        port: 52457
      - name: iopub
        port: 46543
      - name: notification
        port: 40483
      - name: broadcast
        port: 38351
  jupyterServerPort: 80

workers:
  baseHostname: worker
  numReplicas: 12

nfs:
  useLocal: true
  server: 192.168.1.142           # Not needed if useLocal is true
  basePath: "/mnt/nfs_tfm/jupyter"  # Not needed if useLocal is true

users:
  - username: test
    password: $6$5vOSBWhLiy78PwQ7$lyeJUp8F50IYJ0RjLVIfRYjPYffDGludEJf0wNITeCSgflVDhUc7Ho35m5PVl8dlno4kOqxYCafXJsT.STyWQ. #test
  - username: juan
    password: $6$sgH.CvbmRsXExWHL$kNv1POAJd8jzQY3OJ5DunXNVXzpJpCmMT60HxbTnfYfLPTf16ZcaQx4/e1yTth8w5HnG83l/iV8tLeN6lcGpf. #juan
  - username: pedro
    password: $6$edBhu1vMm7ZE3Fov$Q0reW6uZSOoSfe.eMlgOLhKO8qPZmkTZGbCBTewFuie8JwRWnGXEqg9BgTxDSB1iKqerJi8c.8WqXDQmFcHWI0 #pedro
